import { InterviewTemplate } from '../entities/interview-template.entity';

export const INTERVIEW_TEMPLATES: Partial<InterviewTemplate>[] = [
  // ===== FRONTEND =====
  {
    slug: 'react-junior-basics',
    name: 'React — основы (Junior)',
    description:
      'Основы React: компоненты, hooks, state management для начинающих',
    category: 'technical',
    interviewType: 'algorithms',
    applicableRoles: ['frontend', 'fullstack'],
    minLevel: 'junior',
    maxLevel: 'junior_plus',
    skills: ['React', 'JavaScript', 'HTML/CSS'],
    topics: ['Components', 'Hooks', 'State', 'Props'],
    estimatedDuration: 25,
    questionCount: 4,
    difficulty: 'junior',
    isRecommended: true,
    recommendationOrder: 10,
    isActive: true,
    tips: 'Сосредоточьтесь на базовых концепциях React, функциональных компонентах и хуках useState/useEffect',
  },

  {
    slug: 'react-middle-advanced',
    name: 'React — продвинутые паттерны (Middle)',
    description:
      'Продвинутые паттерны React: performance optimization, context, custom hooks',
    category: 'technical',
    interviewType: 'system_design',
    applicableRoles: ['frontend', 'fullstack'],
    minLevel: 'middle',
    maxLevel: 'middle_plus',
    skills: ['React', 'TypeScript', 'Performance'],
    topics: ['Memoization', 'Context API', 'Custom Hooks', 'Performance'],
    estimatedDuration: 40,
    questionCount: 6,
    difficulty: 'middle',
    isRecommended: true,
    recommendationOrder: 15,
    isActive: true,
    tips: 'Готовьтесь к обсуждению оптимизации производительности и сложных паттернов React',
  },

  {
    slug: 'typescript-middle',
    name: 'TypeScript — продвинутый уровень (Middle)',
    description:
      'Продвинутые возможности TypeScript: generics, advanced types, decorators',
    category: 'technical',
    interviewType: 'algorithms',
    applicableRoles: ['frontend', 'fullstack', 'backend'],
    minLevel: 'middle',
    maxLevel: 'senior',
    skills: ['TypeScript'],
    topics: ['Generics', 'Type Inference', 'Advanced Types', 'Decorators'],
    estimatedDuration: 35,
    questionCount: 5,
    difficulty: 'middle',
    isRecommended: true,
    recommendationOrder: 20,
    isActive: true,
  },

  // ===== BACKEND =====
  {
    slug: 'nodejs-junior-basics',
    name: 'Node.js — основы (Junior)',
    description: 'Основы Node.js: async/await, event loop, базовые API',
    category: 'technical',
    interviewType: 'algorithms',
    applicableRoles: ['backend', 'fullstack'],
    minLevel: 'junior',
    maxLevel: 'junior_plus',
    skills: ['Node.js', 'JavaScript', 'Express'],
    topics: ['Event Loop', 'Async/Await', 'Callbacks', 'Basic APIs'],
    estimatedDuration: 30,
    questionCount: 4,
    difficulty: 'junior',
    isRecommended: true,
    recommendationOrder: 25,
    isActive: true,
  },

  {
    slug: 'algorithms-middle',
    name: 'Алгоритмы и структуры данных (Middle)',
    description:
      'Классические алгоритмы и структуры данных для среднего уровня',
    category: 'technical',
    interviewType: 'algorithms',
    applicableRoles: ['backend', 'fullstack', 'frontend'],
    minLevel: 'middle',
    maxLevel: 'middle_plus',
    skills: ['Algorithms', 'Data Structures'],
    topics: ['Trees', 'Graphs', 'Dynamic Programming', 'Sorting'],
    estimatedDuration: 45,
    questionCount: 5,
    difficulty: 'middle',
    isRecommended: true,
    recommendationOrder: 30,
    isActive: true,
  },

  {
    slug: 'system-design-senior',
    name: 'Системное проектирование (Senior)',
    description: 'Проектирование масштабируемых и надежных систем',
    category: 'technical',
    interviewType: 'system_design',
    applicableRoles: ['backend', 'fullstack', 'devops'],
    minLevel: 'middle_plus',
    maxLevel: 'senior',
    skills: ['Architecture', 'Databases', 'Caching', 'Microservices'],
    topics: ['Scalability', 'CAP Theorem', 'Load Balancing', 'Database Design'],
    estimatedDuration: 60,
    questionCount: 4,
    difficulty: 'senior',
    isRecommended: true,
    recommendationOrder: 40,
    isActive: true,
  },

  {
    slug: 'database-design-middle',
    name: 'Проектирование баз данных (Middle+)',
    description:
      'Проектирование баз данных, нормализация, оптимизация запросов',
    category: 'technical',
    interviewType: 'system_design',
    applicableRoles: ['backend', 'fullstack', 'devops'],
    minLevel: 'middle_plus',
    maxLevel: 'senior',
    skills: ['PostgreSQL', 'MySQL', 'Database Design'],
    topics: [
      'Normalization',
      'Indexing',
      'Query Optimization',
      'Transaction Management',
    ],
    estimatedDuration: 50,
    questionCount: 5,
    difficulty: 'middle_plus',
    isRecommended: true,
    recommendationOrder: 35,
    isActive: true,
  },

  // ===== BEHAVIORAL =====
  {
    slug: 'behavioral-all-levels',
    name: 'Поведенческое интервью',
    description:
      'Поведенческое интервью: soft skills, teamwork, problem-solving (STAR метод)',
    category: 'behavioral',
    interviewType: 'behavioral',
    applicableRoles: [],
    minLevel: 'junior',
    maxLevel: 'senior',
    skills: [],
    topics: ['Communication', 'Teamwork', 'Leadership', 'Problem Solving'],
    estimatedDuration: 30,
    questionCount: 5,
    difficulty: 'middle',
    isRecommended: true,
    recommendationOrder: 5,
    isActive: true,
    tips: 'Используйте STAR метод (Situation, Task, Action, Result) при ответе на вопросы. Будьте конкретны и приводите примеры из реального опыта.',
  },

  // ===== HYBRID =====
  {
    slug: 'full-interview-junior',
    name: 'Полное интервью (Junior)',
    description:
      'Комбинированное интервью: базовые технические вопросы и поведенческие',
    category: 'hybrid',
    interviewType: 'full',
    applicableRoles: [],
    minLevel: 'junior',
    maxLevel: 'junior_plus',
    skills: [],
    topics: ['Basics', 'Communication', 'Teamwork'],
    estimatedDuration: 40,
    questionCount: 6,
    difficulty: 'junior',
    isRecommended: true,
    recommendationOrder: 50,
    isActive: true,
  },

  {
    slug: 'full-interview-middle',
    name: 'Полное интервью (Middle)',
    description:
      'Полное интервью: технические и поведенческие вопросы среднего уровня',
    category: 'hybrid',
    interviewType: 'full',
    applicableRoles: [],
    minLevel: 'middle',
    maxLevel: 'middle_plus',
    skills: [],
    topics: ['Algorithms', 'System Design', 'Communication', 'Leadership'],
    estimatedDuration: 60,
    questionCount: 7,
    difficulty: 'middle',
    isRecommended: true,
    recommendationOrder: 55,
    isActive: true,
  },

  // ===== TEST (для знакомства) =====
  {
    slug: 'test-intro',
    name: 'Пробное интервью (знакомство)',
    description: 'Легкое пробное интервью для знакомства с форматом',
    category: 'behavioral',
    interviewType: 'test',
    applicableRoles: [],
    minLevel: 'junior',
    maxLevel: 'senior',
    skills: [],
    topics: ['Introduction', 'Getting Started'],
    estimatedDuration: 10,
    questionCount: 3,
    difficulty: 'junior',
    isRecommended: true,
    recommendationOrder: 1,
    isActive: true,
  },

  // ===== ДОПОЛНИТЕЛЬНЫЕ =====
  {
    slug: 'css-advanced-middle',
    name: 'CSS — продвинутый уровень (Middle)',
    description:
      'Продвинутые возможности CSS: flexbox, grid, animations, responsive design',
    category: 'technical',
    interviewType: 'algorithms',
    applicableRoles: ['frontend', 'fullstack'],
    minLevel: 'middle',
    maxLevel: 'middle_plus',
    skills: ['CSS', 'HTML'],
    topics: ['Flexbox', 'Grid', 'Animations', 'Responsive Design'],
    estimatedDuration: 30,
    questionCount: 4,
    difficulty: 'middle',
    isRecommended: false,
    recommendationOrder: 60,
    isActive: true,
  },

  {
    slug: 'rest-api-middle',
    name: 'Проектирование REST API (Middle)',
    description: 'Проектирование REST API: принципы, security, versioning',
    category: 'technical',
    interviewType: 'system_design',
    applicableRoles: ['backend', 'fullstack'],
    minLevel: 'middle',
    maxLevel: 'middle_plus',
    skills: ['REST', 'API Design', 'HTTP'],
    topics: [
      'REST Principles',
      'Authentication',
      'Error Handling',
      'Versioning',
    ],
    estimatedDuration: 35,
    questionCount: 4,
    difficulty: 'middle',
    isRecommended: false,
    recommendationOrder: 65,
    isActive: true,
  },

  {
    slug: 'sql-intermediate',
    name: 'SQL — средний уровень',
    description:
      'SQL для среднего уровня: joins, subqueries, optimization, transactions',
    category: 'technical',
    interviewType: 'algorithms',
    applicableRoles: ['backend', 'fullstack', 'devops'],
    minLevel: 'middle',
    maxLevel: 'middle_plus',
    skills: ['SQL', 'PostgreSQL', 'MySQL'],
    topics: ['Joins', 'Subqueries', 'Window Functions', 'Query Optimization'],
    estimatedDuration: 40,
    questionCount: 5,
    difficulty: 'middle',
    isRecommended: false,
    recommendationOrder: 70,
    isActive: true,
  },
];
