/* eslint-disable @typescript-eslint/no-unsafe-return */
import { Injectable, Logger } from '@nestjs/common';
import Cartesia from '@cartesia/cartesia-js';
import type { TTSWSContext } from '@cartesia/cartesia-js/resources/tts/ws.js';

const SENTENCE_BOUNDARIES = /[.!?,]/;

@Injectable()
export class CartesiaTtsService {
  private readonly logger = new Logger(CartesiaTtsService.name);
  private readonly client = new Cartesia({
    apiKey: process.env.CARTESIA_API_KEY,
  });

  async streamAudio(
    tokenStream: AsyncGenerator<string>,
    onChunk: (buf: Buffer) => void,
    isCancelled: () => boolean,
    language: 'ru' | 'en' = 'ru',
  ): Promise<void> {
    this.logger.log(
      `[streamAudio] ▶️  START: language=${language} voiceId=${process.env.CARTESIA_VOICE_ID}`,
    );

    const ws = await this.client.tts.websocket();
    this.logger.log(`[streamAudio] ✅ Cartesia WebSocket connected`);

    const context = ws.context({
      model_id: 'sonic-2-2025-03-07',
      voice: { id: process.env.CARTESIA_VOICE_ID!, mode: 'id' },
      output_format: {
        container: 'raw',
        encoding: 'pcm_s16le',
        sample_rate: 16000,
      },
    });
    this.logger.log(
      `[streamAudio] 🎙️  TTS context created: sonic-2-2025-03-07`,
    );

    await Promise.all([
      this._pushTokens(tokenStream, context, isCancelled, language),
      this._receiveAudio(context, onChunk, isCancelled),
    ]);

    this.logger.log(`[streamAudio] ✅ DONE: TTS complete, closing connection`);
    ws.close();
  }

  private async _pushTokens(
    tokenStream: AsyncGenerator<string>,
    context: TTSWSContext,
    isCancelled: () => boolean,
    language: 'ru' | 'en',
  ): Promise<void> {
    const sendChunk = (transcript: string, cont: boolean) =>
      (context as any)._ws.send({
        model_id: 'sonic-2-2025-03-07',
        voice: { id: process.env.CARTESIA_VOICE_ID!, mode: 'id' },
        output_format: {
          container: 'raw',
          encoding: 'pcm_s16le',
          sample_rate: 16000,
        },
        language,
        transcript,
        context_id: context.contextId,
        continue: cont,
      });

    let buffer = '';
    let chunkCount = 0;

    for await (const token of tokenStream) {
      if (isCancelled()) {
        this.logger.log(`[_pushTokens] ⏸️  Cancelled, stopping TTS`);
        break;
      }
      buffer += token;
      if (SENTENCE_BOUNDARIES.test(buffer)) {
        this.logger.log(
          `[_pushTokens] 📤 Sending TTS chunk #${chunkCount + 1}: "${buffer}"`,
        );
        await sendChunk(buffer, true);
        buffer = '';
        chunkCount++;
      }
    }

    if (buffer.trim() && !isCancelled()) {
      this.logger.log(`[_pushTokens] 📤 Sending final TTS chunk: "${buffer}"`);
      await sendChunk(buffer, true);
      chunkCount++;
    }

    this.logger.log(
      `[_pushTokens] ✅ Sent ${chunkCount} TTS chunks to Cartesia, waiting for audio...`,
    );
    if (chunkCount > 0) {
      await context.no_more_inputs();
    }
  }

  private async _receiveAudio(
    context: TTSWSContext,
    onChunk: (buf: Buffer) => void,
    isCancelled: () => boolean,
  ): Promise<void> {
    let audioChunkCount = 0;
    for await (const event of context.receive()) {
      if (isCancelled()) break;
      if (event.type === 'chunk' && event.audio) {
        audioChunkCount++;
        if (audioChunkCount <= 3 || audioChunkCount % 10 === 0) {
          this.logger.log(
            `[_receiveAudio] 🔊 Audio chunk #${audioChunkCount} size=${event.audio.length} bytes`,
          );
        }
        onChunk(event.audio);
      }
    }
    this.logger.log(
      `[_receiveAudio] ✅ Total audio chunks generated by Cartesia: ${audioChunkCount}`,
    );
  }
}
